appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: native}
travis:
  secure: {BINSTAR_TOKEN: CfEhrnz7PTQl7C6RZl4e42IuC/jtdA6A6Dl3je3mTGJgBCmG9lE/G70JOJ14L29RauSMUaMRjeeNqK4CETKhHysU2gDAJ8UiWf7Btq8dsXcUO19D9JdHQnfrs0pG6HK2/Ba6StbEfW9I97aFw5JGQmY21+8UyNTTaczl63RD621eFmLb6NKTT3VRG+CnY35GB6+SxgYh6b5D+s0+ScU2EdVNcyWtTKCYMhyijclBqNGljchig+3yIQJXWKdEdpndJIHARPsCeBlbA3dgkPsB9CaskUgGLOdvAM5q9glFCrSMTVKH76zg6GX7Ly950Pnpi8DUzJgKv4RXZBHbNxjBWKXV/OAlpCgpT+EbK9D5qb3hPcM/LrYcpx1rpjKHh/l4Ta+Hp9DmoViKwGgpzrLUBtKFJn8jAcTxM1NFRMZLWAkPJSwpgPjq1oVpAmaWdz11DhyknZOkRe6PjxbVQyIvZzM0Oka54ynXZBjLeHFa03d6pM1LsCz+uCHL7DHDTOrJatyEtgmin6BGk+bANjP108XEBBASKvyBRiK1ZZQPxsHt04ahb2tgkH085geHRkH4qOjzPIT9yCiWaLdMpM/cmZJU7CNlFJd8IQWZB3p5vWbZtd/WD/aEQBvkY03H2AiqxKVVVE/bGYe2nLiH4g8Hlk8wfjWbvSOgagUjcIcJ8TA=}
